version: '3'
volumes:
  grafana:
services:
  grafana:
    image: grafana/grafana
    restart: always
    ports:
    - 3000:3000
    volumes:
    - grafana:/var/lib/grafana
      
# docker-compose -f compose.yaml  up -d 