version: '3'
volumes:
  db_data:
  app_data:
  cache_volume:
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
    - 3306:3306
    volumes:
    - db_data:/var/lib/mysql
  redis:
    depends_on:
    - mysql
    image: redis
    ports:
    - 6379:6379
  wordpress:
    depends_on:
    - mysql
    - redis
    restart: always
    image: wordpress:4.9.0
    ports:
    - 80:80
    volumes:
    - app_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

# docker-compose -f compose.yaml  up -d 