version: '3'
volumes:
  jenkins:
services:
  jenkins:
    image: jenkins/jenkins
    restart: always
    ports:
    - 8080:8080
    volumes:
    - jenkins:/var/lib/jenkins
      
# docker-compose -f compose.yaml  up -d 